# Generated by Django 5.2.4 on 2025-07-23 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
        migrations.RemoveField(
            model_name='car',
            name='driers',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='licence_number',
        ),
        migrations.AddField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(default='ABC1234', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.manufacturer'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
